# install numpy library

In [1]:
!pip install numpy

# import numpy

In [2]:
import numpy 

In [3]:
newnum = numpy.array([1,2,3,4,5])

In [4]:
print(newnum)

[1 2 3 4 5]


# using alias with numpy

In [25]:
import numpy as np

In [6]:
arr = np.array([5,6,7])

In [7]:
print(arr)

[5 6 7]


In [8]:
# np. to check the functions numpy has

# check numpy version

In [9]:
print(np.__version__)

1.24.3


# creating an array with numpy (type)

In [10]:
hh = np.array([55,66,77])

In [11]:
print(hh)
print(type(hh))

[55 66 77]
<class 'numpy.ndarray'>


# To create an ndarray, we can pass a list,tuple or any array-like object into the array

In [12]:
lp = np.array([89,34,88])

In [13]:
print(lp)

[89 34 88]


# dimensions in array


# 0-D Arrays

In [14]:
so = np.array(78)
print(so)

78


# 1-D Arrays

In [15]:
kk = np.array([23,45,67,89])
print(kk)

[23 45 67 89]


# 2-D Arrays

In [16]:
uu = np.array([[1,2,3], [4,5,6]])
print(uu)

[[1 2 3]
 [4 5 6]]


# 3-D Arrays

In [17]:
pp = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,9,5]]])
print(pp)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 9 5]]]


# To check the number of dimensions that an array has

# ndim() method

In [18]:
print(so.ndim)
print(kk.ndim)
print(uu.ndim)
print(pp.ndim)

0
1
2
3


# set the number of dimension

In [19]:
arr = np.array([1,2,3], ndmin = 5)
print(arr)

[[[[[1 2 3]]]]]


# indexing

In [20]:
art = np.array([1,2,3])
print(art[1])

2


# Access 2D array

In [21]:
jk = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element on ist row: ", jk[0,1])

2nd element on ist row:  2


In [22]:
jk = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("5th element on 2nd row: ", jk[1,4])

5th element on 2nd row:  10


# Access 3D array

In [23]:
mn = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(mn[0,1,2])

6


# Negative indexing

In [24]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Array slicing

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


# Negative slicing

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


# STEP

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


# Slicing 2D array

In [37]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [39]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [40]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Checking the data type of an array

In [46]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [48]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# Creating Arrays With a Defined Data Type

In [42]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [49]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Converting Data Type on Existing Arrays

In [51]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [53]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Copy method

In [55]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# view method

In [56]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]
