OKAFOR CHIAMAKA

In [1]:
import numpy as np

# (1.) Access the following elements in these array
(a.) Access 67
aa = np.array([[1,2,[89,67,47],3,4,5], [6,7,8,9,10]])

In [2]:
# aa = np.array([[1,2,[89,67,47],3,4,5], [6,7,8,9,10]])
# print(aa)

(b.) Access 84
bc = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10,[12,55,84], 11, 12]]])
c. Using negative indexing access 7
rr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


In [3]:
# bc = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10,[12,55,84], 11, 12]]])
# print(bc)

In [4]:
 rr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(rr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print(rr[1, -4])

7


# (2a) make a copy of this array, make a change of one of the element in the original array, make sure it doesn't affect the copied one
uu = np.array([1, 2, 3, 4, 5])


In [6]:
uu = np.array([1, 2, 3, 4, 5])
jj = uu.copy()
uu[1] = 9
print(uu)
print(jj)

[1 9 3 4 5]
[1 2 3 4 5]


# (2b.) make a copy of this array, make a change of one of the element in the original array, let the changes you make affect the copied one
hh = np.array([55,47,58,66])

In [7]:
hh = np.array([55,47,58,66])
nw = hh.view()
hh[2] = 90
print(hh)
print(nw)

[55 47 90 66]
[55 47 90 66]


# (3a.) Reshape this array into 2-D array
ww = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [8]:
ww = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
ht = ww.reshape(3,4)
print(ht)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# (3b.) Reshape From 1-D to 3-D
jj = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [9]:
jj = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
kl = jj.reshape(2,2,3)
print(kl)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# (4.) Flatten these arrays
(a.) po = np.array([[1, 2, 3], [4, 5, 6]])
(b.) lo = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [10]:
po = np.array([[1, 2, 3], [4, 5, 6]])
yes = po.reshape(-1)
print(yes)

[1 2 3 4 5 6]


In [11]:
lo = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
no = lo.reshape(-1)
print(no)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


# (5) Iterate on the elements of the following arrays
a. ww = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b. po = np.array([[1, 2, 3], [4, 5, 6]])
c. lo = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [12]:
ww = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
for y in ww:
    print(y)


1
2
3
4
5
6
7
8
9
10
11
12


In [13]:
po = np.array([[1, 2, 3], [4, 5, 6]])
for x in po:
    print(x)

[1 2 3]
[4 5 6]


In [14]:
lo = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for z in lo:
    print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


# (6a.) Join these arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
pp = np.concatenate((arr1, arr2))
print(pp)


[1 2 3 4 5 6]


# (6b.) Split this array into 4 part
jj = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [16]:
jj = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
ter = np.array_split(jj,4)
print(ter)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


# (7) Search through these arrays
a. find the index where the value is 10
rp = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [17]:
rp = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
z = np.where(rp == 10)
print(z)

(array([9], dtype=int64),)


b. find the index where the value is 5
up = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [18]:
up = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
off = np.where(up == 5)
print(off)

(array([4], dtype=int64),)


# (8.) Create a new array from the elements in this 1-D array with (41,44)
yt = np.array([41, 42, 43, 44])

In [20]:
yt = np.array([41, 42, 43, 44])
new = []
for element in yt:
    if element < 42:
        new.append(True)
    elif element > 43:
        new.append(True)
    else:
        new.append(False)
        
new_element = yt[new]
print(new)
print(new_element)

[True, False, False, True]
[41 44]
